#!/bin/bash
NUMBER=$1

if [ $NUMBER -gt 20 ]; then
    echo "number is $NUMBER greater than 20"
    elif [ $NUMBER -eq 20 ]; then

     echo "number is $NUMBER equal 20"
     else

    echo "number is $NUMBER less than 20"
fi
