#!/bin/bash
USERID=$(id -u )

if [ $USERID -ne 0 ]; then
   echo "please run this script as root user"
   exit 1
fi 
echo "installing nginx" 
dnf remove nginx -y

 if [ "$?" -ne 0 ]; then
    echo "nginx remove failed"
    exit 1
    else
    echo "nginx removed successfully"
 fi